
[opts]

autoread = true
backup = false
clipboard = "unnamed,unnamedplus"
expandtab = true
foldlevel = 6
formatoptions = "cr"
guicursor = "a:hor20"
ignorecase = true
incsearch = true
linespace = 2
magic = true
shortmess = "ltToOCFI"
laststatus = 0
number = true
showmode = false
wrap = true
scrolloff = 8
hlsearch = false
shiftwidth = 2
smartcase = true
smarttab = true
ruler = false
splitbelow = true
splitright = true
swapfile = false
tabstop = 2
termguicolors = true
writebackup = false

