
[settings]

host = "nixos"
user = "lynx"

[scheme]

# Catppuccin Mocha
base00 = "#11111b"
base01 = "#181825"
base02 = "#313244"
base03 = "#45475a"
base04 = "#585b70"
base05 = "#cdd6f4"
base06 = "#f5e0dc"
base07 = "#b4befe"
base08 = "#f38ba8"
base09 = "#fab387"
base0A = "#f9e2af"
base0B = "#a6e3a1"
base0C = "#94e2d5"
base0D = "#89b4fa"
base0E = "#cba6f7"
base0F = "#f2cdcd"

# # Rose Pine Normal
# base00 = "#191724"
# base01 = "#1f1d2e"
# base02 = "#26233a"
# base03 = "#6e6a86"
# base04 = "#908caa"
# base05 = "#e0def4"
# base06 = "#e0def4"
# base07 = "#524f67"
# base08 = "#eb6f92"
# base09 = "#f6c177"
# base0A = "#ebbcba"
# base0B = "#31748f"
# base0C = "#9ccfd8"
# base0D = "#c4a7e7"
# base0E = "#f6c177"
# base0F = "#524f67"

# # Gruvbox Dark Medium
# base00 = "#282828"
# base01 = "#3c3836"
# base02 = "#504945"
# base03 = "#665c54"
# base04 = "#bdae93"
# base05 = "#d5c4a1"
# base06 = "#ebdbb2"
# base07 = "#fbf1c7"
# base08 = "#fb4934"
# base09 = "#fe8019"
# base0A = "#fabd2f"
# base0B = "#b8bb26"
# base0C = "#8ec07c"
# base0D = "#83a598"
# base0E = "#d3869b"
# base0F = "#d65d0e"


