
noice.enable = true
neogit.enable = true
comment.enable = true
auto-save.enable = true
which-key.enable = true
telescope.enable = true
treesitter.enable = true
conform-nvim.enable = true
web-devicons.enable = true
nvim-colorizer.enable = true
nvim-autopairs.enable = true
markdown-preview.enable = true

cmp-path.enable = true
cmp-buffer.enable = true
cmp-nvim-lsp.enable = true
cmp-treesitter.enable = true

[cmp]
enable = true
settings.experimental.ghost_text = true
autoEnableSources = false

[cmp.settings.mapping]
"<Down>" = "cmp.mapping(cmp.mapping.select_next_item(), { 'i', 's' })"
"<Up>" = "cmp.mapping(cmp.mapping.select_prev_item(), { 'i', 's' })"
"<Tab>" = "cmp.mapping.confirm({ select = true })"

[[cmp.settings.sources]]
name = "lsp"
priority = 100

[[cmp.settings.sources]]
name = "treesitter"
keyword_length = 2
priority = 90

[[cmp.settings.sources]]
name = "emoji"
option.insert = false
priority = 75

[[cmp.settings.sources]]
name = "path"
keyword_length = 2
priority = 60

[[cmp.settings.sources]]
name = "buffer"
keyword_length = 2
priority = 50

[lsp]
enable = true
servers.nixd.enable = true
servers.statix.enable = true

[nvim-tree]
enable = true
filters.dotfiles = true
filters.custom = [ "^.git", "*.lock" ]
view.side = "right"

[telescope.keymaps]
"<leader>f" = "find_files"
"<leader>n" = "live_grep"
