
lsp.enable = true
cmp.enable = true
noice.enable = true
neogit.enable = true
comment.enable = true
auto-save.enable = true
which-key.enable = true
telescope.enable = true
conform-nvim.enable = true
web-devicons.enable = true
nvim-colorizer.enable = true
nvim-autopairs.enable = true
markdown-preview.enable = true

[lsp.servers]
nixd.enable = true
statix.enable = true

[telescope.keymaps]
"<leader>f" = "find_files"
"<leader>n" = "live_grep"

[cmp.settings.experimental]
ghost_text = true

[cmp.settings.mapping]
"<Down>" = "cmp.mapping(cmp.mapping.select_next_item(), { 'i', 's' })"
"<Up>" = "cmp.mapping(cmp.mapping.select_prev_item(), { 'i', 's' })"
"<Tab>" = "cmp.mapping.confirm({ select = true })"

[[cmp.settings.sources]]
name = "lsp"

[[cmp.settings.sources]]
name = "path"
keyword_lenght = 2

[[cmp.settings.sources]]
name = "emoji"
keyword_lenght = 2

[[cmp.settings.sources]]
name = "buffer"
keyword_lenght = 2
