#!/usr/bin/env sh

set -euo pipefail

nixos-generate-config --show-hardware-config \
  | sed -e '1,3d' \
  | sed -e '1 i\# This file is autogenerated. See flake.nix or readme.md instead.' \
  > "$1.nix"


