#!/usr/bin/env sh

set -euo pipefail

export message="This file is autogenerated. See flake.nix or readme.md instead."

nixos-generate-config --show-hardware-config \
  | sed -e '1,3d' \
  | sed -e "1 i\# $message" \
  > "$1.nix"


