
# Window padding on borders.
[window.padding]
x = 8 # left - right
y = 10 # down - up

# Cursor settings.
[cursor]
thickness = 0.35

# Don't change shape when window out of focus.
unfocused_hollow = false 

style.shape = "Underline"
