
# Loae config changed in the ui.
loadAutoconfig = true

# List of search engines prefixes. 'DEFAULT' is the default search engine.
[searchEngines]
DEFAULT = "https://search.hbubli.cc/search?q={}"
gh = "https://github.com/search?q={}"
in = "https://cal1.iv.ggtyler.dev/search?q={}"
np = "https://search.nixos.org/packages?channel=24.05&query={}"
od = "https://odysee.com/$/search?q={}"
pi = "https://cal1.pi.ggtyler.dev/results?search_query={}"

[settings]
zoom.levels = [ "10", "20", "30", "40", "50", "60", "70", "80", "90", "100", "110", "120", "130", "140", "150", "160", "170", "180", "190", "200", "210", "220", "230", "240", "250" ]

# Keybinds in normal mode.
[keyBindings.normal]
aa = "hint all yank"
aj = "hint all hover"
as = "hint all delete"
xe = "config-cycle colors.webpage.darkmode.enabled true false"
xt = "config-cycle tabs.position top right"
xx = "config-cycle tabs.show multiple never"
e = "tab-close"
"=" = "zoom-in -q"
- = "zoom-out -q"
1 = "tab-select 1"
2 = "tab-select 2"
3 = "tab-select 3"
4 = "tab-select 4"
5 = "tab-select 5"
6 = "tab-select 6"
7 = "tab-select 7"
8 = "tab-select 8"
9 = "tab-select 9"
0 = "tab-select 10"
