
enable = true

[keyboards.main]
config = """
(defsrc
  esc 
  tab 
  caps
  h j k l 
  n g
  e d
)

(deflayer base
  caps 
  (tap-hold 75 150 tab (layer-while-held nav))
  (tap-hold 75 150 esc lctl)
  h j k l 
  g n
  d e
)

(deflayer nav
  _
  _
  _
  left down up right
  _ _
  _ _
)
"""
