
[services]

openssh.enable = true

# Enable touchpad support.
libinput.enable = true

[services.displayManager.ly]

enable = true
settings.vi_mode = true

[systemd.targets]

# Disable sleep.
sleep.enable = false
suspend.enable = false
hibernate.enable = false
hybrid-sleep.enable = false

