
# Enable wi-fi support via network manager.
networking.networkmanager.enable = true

# Set host name, required to rebuiled the system.
networking.hostName = "nixos"

# Set your time zone.
time.timeZone = "Europe/Warsaw"

# Enable firewall.
networking.firewall.enable = true

# Bluetooth settings.
[hardware.bluetooth]

# Enable bluetooth and make it power on boot.
enable = true
powerOnBoot = true

# Kanata settings.
[services.kanata]

# Enable kanata and make it process all keys.
enable = true
keyboards.main.extraDefCfg = "process-unmapped-keys yes"

# Service settings.
[services]

# Enable SSH.
openssh.enable = true

# Enable bluetooth support via bluetooth manager.
blueman.enable = true

# Enable touchpad support.
libinput.enable = true

# Nixos system settings for ly display manager.
[services.displayManager.ly]

enable = true
settings.vi_mode = true

# Nixos system settings for systemd services targets.
[systemd.targets]

# Disable sleep.
sleep.enable = false
suspend.enable = false
hibernate.enable = false
hybrid-sleep.enable = false

[security]
doas.enable = true

sudo.enable = false

# Removes password prompts for your wheel group,
# you can manage user groups below at '[users.users.*]'.
doas.wheelNeedsPassword = false

# Nixos system settings for programs.
[programs]

# Enable gnupg.
gnupg.agent.enable = true

# Enable zsh shell.
zsh.enable = true

# Disable nano, you can get it back using 'nix-shell -p nano'.
nano.enable = false


# Boot loader settings, required to rebuiled the system.
[boot.loader]
systemd-boot.enable = true
efi.canTouchEfiVariables = true

# User configuration.
[users.users.lynx]

# Makes user not have super user access.
isNormalUser = true

homix = true

# Set extra groups for user.
extraGroups = ["wheel"]
