
# Window padding on borders.
[window.padding]
x = 8 # left - right
y = 9 # down - up

[window]
opacity = 0.85

[font]
bold_italic.family = "JetBrainsMono Nerd Font"
normal.family = "JetBrainsMono Nerd Font"
italic.family = "JetBrainsMono Nerd Font"
bold.family = "JetBrainsMono Nerd Font"

[cursor]
thickness = 0.35
unfocused_hollow = false 
style.shape = "Underline"
