
# One off binds.
bind = [
  "SUPER, Q, exit",
  "SUPER, C, killactive",
  "SUPER, F, exec, alacritty",
  "SUPER, T, exec, qutebrowser",
  ", F2, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 3%-",
  ", F3, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 3%+",
  "SUPER CTRL, H, movewindow, l",
  "SUPER CTRL, J, movewindow, d",
  "SUPER CTRL, K, movewindow, u",
  "SUPER CTRL, L, movewindow, r",
  "SUPER SHIFT, 1, movetoworkspacesilent, 1",
  "SUPER SHIFT, 2, movetoworkspacesilent, 2",
  "SUPER SHIFT, 3, movetoworkspacesilent, 3",
  "SUPER SHIFT, 4, movetoworkspacesilent, 4",
  "SUPER SHIFT, 5, movetoworkspacesilent, 5",
  "SUPER SHIFT, 6, movetoworkspacesilent, 6",
  "SUPER SHIFT, 7, movetoworkspacesilent, 7",
  "SUPER SHIFT, 8, movetoworkspacesilent, 8",
  "SUPER SHIFT, 9, movetoworkspacesilent, 9",
  "SUPER, 1, workspace, 1",
  "SUPER, 2, workspace, 2",
  "SUPER, 3, workspace, 3",
  "SUPER, 4, workspace, 4",
  "SUPER, 5, workspace, 5",
  "SUPER, 6, workspace, 6",
  "SUPER, 7, workspace, 7",
  "SUPER, 8, workspace, 8",
  "SUPER, 9, workspace, 9",
  "SUPER, H, movefocus, l",
  "SUPER, J, movefocus, d",
  "SUPER, K, movefocus, u",
  "SUPER, L, movefocus, r",
]

# Binds that repeat on hold.
binde = [
  "SUPER SHIFT, H, resizeactive, -3%  0%",
  "SUPER SHIFT, J, resizeactive,  0%  3%",
  "SUPER SHIFT, K, resizeactive,  0% -3%",
  "SUPER SHIFT, L, resizeactive,  3%  0%",
]

# Disable animations.
animations.enabled = false

# Decoration settings.
[decoration]
blur.enabled = false
drop_shadow = false

# Cursor settings.
[cursor]
hide_on_key_press = true

# General settings.
[general]
"col.active_border" = "rgb(45475a)"
"col.inactive_border" = "rgb(1e1e2e)"
layout = "master"
gaps_in = 8
gaps_out = 12
border_size = 0

# Master layout settings.
[master]
allow_small_split = true
mfact = 0.6
new_status = "slave"
orientation = "right"

# Dwindle layout settings.
[dwindle]
pseudotile = true
smart_split = true

# Input settings.
[input]
repeat_delay = 175
repeat_rate = 50

# Misc settings.
[misc]
allow_session_lock_restore = true
animate_manual_resizes = true
animate_mouse_windowdragging = true
disable_hyprland_logo = true
disable_splash_rendering = true
enable_swallow = true
force_default_wallpaper = true
vfr = true

