# https://inv.nadeko.net/watch?v=G5f6GC7SnhU
# https://github.com/colemickens/nixcfg/tree/main/secrets

creation_rules:
  - path_regex: .*$
    key_groups:
    - age: [ age14vlk7dpr4dkznvzhwv6l38yuxc9u6nucu8a4r8jja96mvga503jq9f904g ]
